# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DTALikelihoodC <- function(ED, fit_mig_mat, node_indices) {
    .Call('_StructCoalescent_DTALikelihoodC', PACKAGE = 'StructCoalescent', ED, fit_mig_mat, node_indices)
}

#' @title Deme Decomposition
#' @description Counts the number of each type of migration event and deme of each coalescence event
#' @param ED Extended data representation of a migration history
#' @param n_deme Number of demes
#' @param node_indices Vector with element i giving row index of label i (NA if not present)
#' @returns m Matrix giving number of each type of migration observed
#' @returns c Vector giving number of coalescences per deme
#' @export
#'
DemeDecompC <- function(ED, n_deme, node_indices) {
    .Call('_StructCoalescent_DemeDecompC', PACKAGE = 'StructCoalescent', ED, n_deme, node_indices)
}

#' @title Forward-in-time migration matrix conversion
#' @description Computes the forward-in-time migration matrix associated with a given backwards-in-time migration matrix, coalescent rate and time scale
#' @param bit_mm NumericMatrix Backward-in-time migration matrix
#' @param coal_rate NumericVector Coalescent rates
#' @returns NumericMatrix Forward-in-time migration matrix
#'
#' @export
#'
FitMigMatC <- function(bit_mm, coal_rate) {
    .Call('_StructCoalescent_FitMigMatC', PACKAGE = 'StructCoalescent', bit_mm, coal_rate)
}

#' @title Backward-in-time migration matrix conversion
#' @description Computes the backward-in-time migration matrix associated with a given forward-in-time migration matrix, coalescent rate and time scale
#' @param bit_mm NumericMatrix Forward-in-time migration matrix
#' @param coal_rate NumericVector Coalescent rates
#' @returns NumericMatrix Backward-in-time migration matrix
#' @export
#'
BitMigMatC <- function(fit_mm, coal_rate) {
    .Call('_StructCoalescent_BitMigMatC', PACKAGE = 'StructCoalescent', fit_mm, coal_rate)
}

#' @title NodeCountC
#' @description Counts the number of migrations between pairs of demes, and coalescences within each deme
#' @param ED NumericMatrix Extended data object representing structured phylogeny
#' @param n_deme int Number of demes modelled under ED
#' @param node_indices NumericVector Vector giving row numbers in ED for node labels
#' @returns List containing matrix m with element (i,j) giving the number of migrations i -> j backwards in time, and a vector c with element i giving the number of coalescences occurring in deme i
#'
#' @export
#'
NodeCountC <- function(ED, n_deme, node_indices) {
    .Call('_StructCoalescent_NodeCountC', PACKAGE = 'StructCoalescent', ED, n_deme, node_indices)
}

#' @title Node Indices
#' @description Returns a vector giving the row indices of the labels in ED
#' @param ED NumericMatrix Extended data object representing structured coalescent genealogy
#'
#' @export
#'
NodeIndicesC <- function(ED) {
    .Call('_StructCoalescent_NodeIndicesC', PACKAGE = 'StructCoalescent', ED)
}

SC_like_C <- function(ED, coal_rate, bit_mig_mat, node_indices) {
    .Call('_StructCoalescent_SC_like_C', PACKAGE = 'StructCoalescent', ED, coal_rate, bit_mig_mat, node_indices)
}

#' Sample path from the distribution of an endpoint-conditioned CTMC
#'
#' Simulate a sample path from an endpoint conditioned CTMC by uniformization
#' using a pre-computed transition probability matrix.
#' Taken from ECctmc-0.2.5 under a GPL-3 license
#'
#' @param a,b States at the interval endpoints, provided as integers
#'    corresponding to rows of the CTMC rate matrix.
#' @param t0,t1 times of the interval endpoints
#' @param Q CTMC rate matrix
#' @param P CTMC transition probability matrix over the interval.
#'
#' @return matrix whose first column is the sequence of transition times
#' bookended by interval endpoints, and whose second column is the sequence of
#' states
#' @author Jon Fintzi (ECctmc-0.2.5)
sample_path <- function(a, b, t0, t1, Q, P) {
    .Call('_StructCoalescent_sample_path', PACKAGE = 'StructCoalescent', a, b, t0, t1, Q, P)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_StructCoalescent_RcppExport_registerCCallable', PACKAGE = 'StructCoalescent')
})
