# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Forward-in-time migration matrix conversion
#' @description Computes the forward-in-time migration matrix associated with a given backwards-in-time migration matrix, coalescent rate and time scale
#' @param bit_mm NumericMatrix Backward-in-time migration matrix
#' @param coal_rate NumericVector Coalescent rates
#' @returns NumericMatrix Forward-in-time migration matrix
#'
#' @export
#'
FitMigMatC <- function(bit_mm, coal_rate) {
    .Call('_StructCoalescent_FitMigMatC', PACKAGE = 'StructCoalescent', bit_mm, coal_rate)
}

#' @title Backward-in-time migration matrix conversion
#' @description Computes the backward-in-time migration matrix associated with a given forward-in-time migration matrix, coalescent rate and time scale
#' @param bit_mm NumericMatrix Forward-in-time migration matrix
#' @param coal_rate NumericVector Coalescent rates
#' @returns NumericMatrix Backward-in-time migration matrix
#' @export
#'
BitMigMatC <- function(fit_mm, coal_rate) {
    .Call('_StructCoalescent_BitMigMatC', PACKAGE = 'StructCoalescent', fit_mm, coal_rate)
}

#' @title Node Indices
#' @description Returns a vector giving the row indices of the labels in ED
#' @param ED NumericMatrix Extended data object representing structured coalescent genealogy
#'
#' @export
#'
NodeIndicesC <- function(ED) {
    .Call('_StructCoalescent_NodeIndicesC', PACKAGE = 'StructCoalescent', ED)
}

#' @title SC_like_C
#' @description Computes the likelihood of a structured coalescent genealogy
#' @param ED NumericMatrix Extended data object representing structured phylogeny
#' @param coal_rate NumericVector Effective population of each deme
#' @param mig_mat NumericMatrix Backwards-in-time migration rates between pairs of demes
#' @param node_indices NumericVector Vector giving row numbers in ED for node labels
#' @returns List containing log-likelihood and likelihood of the structured coalescent genealogy
#'
#' @export
#'
SC_like_C <- function(ED, coal_rate, bit_mig_mat, node_indices) {
    .Call('_StructCoalescent_SC_like_C', PACKAGE = 'StructCoalescent', ED, coal_rate, bit_mig_mat, node_indices)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_StructCoalescent_RcppExport_registerCCallable', PACKAGE = 'StructCoalescent')
})
